### PR TITLE
Test AppVeyor build artifacts for foreign PRs

### PR DESCRIPTION
**Pull request by dhimmel**
Refs https://github.com/manubot/rootstock/issues/198#issuecomment-517663946

### CODE REVIEW

**Comment by dhimmel** [comment]
The seems to have uploaded the artifact [here](https://ci.appveyor.com/project/agitter/my-manuscript/builds/26432662/artifacts):

> image

The URL provided in the [log](https://ci.appveyor.com/project/agitter/my-manuscript/builds/26432662#L368) is

```
https://ci.appveyor.com/api/projects/agitter/my-manuscript/artifacts/output/manuscript.pdf?branch=master
```

This seems to be incorrect (see `master` branch). I think we want the log to give the artifact link specific to that build if possible. Perhaps we want to print a link like:

```
https://ci.appveyor.com/project/agitter/my-manuscript/builds/26432662/artifacts
```

**Comment by agitter** [comment]
Thanks for testing the behavior with a foreign PR.  I was able to use different AppVeyor environment variables to add the following in the build log:
```
Artifacts available from https://ci.appveyor.com/project/agitter/my-manuscript/builds/26434055/artifacts
Updated PDF available from https://ci.appveyor.com/api/buildjobs/rx732p73bbbuo027/artifacts/output%2Fmanuscript.pdf
```

**Comment by dhimmel** [comment]
The AppVeyor implementation of artifacts is great... having them right next to the job that created them. My only complaint would be the backslash in `output\manubot.pdf`. The syntax to add them to the build is also quite simple. It looks like GitLab also has a nice artifacts [interface](https://docs.gitlab.com/ee/user/project/pipelines/job_artifacts.html), but this doesn't do us any good if we're using GitHub.

**Comment by agitter** [comment]
@dhimmel I tested AppVeyor GitHub notifications in #6.  There you can see different scenarios with a single artifact, multiple artifacts, and a failed build.  These make it even easier to inspect the updated manuscript as part of the pull request review process.

If everything works as intended, we should get a notification here soon for my edit in f7d32980b308a05a5e90dd36dc71a7a06422ae94

**Pull request merged**
