### PR TITLE
Test GitHub notifications

### PR DESCRIPTION
**Pull request by agitter**
See https://www.appveyor.com/docs/notifications/#github-pull-request

### CODE REVIEW

**Comment by dhimmel** [comment]
Wow this is cool. I wonder if we should rename manuscript.pdf to be like `manuscript-jobid.pdf`. Also is there a way to suppress notifications for a PR, like saying @AppVeyorBot be quite!

**Comment by dhimmel** [comment]
It's fun to see all of @AppVeyorBot's comments at https://github.com/search?o=desc&q=commenter%3AAppVeyorBot&s=created&type=Issues

**Comment by agitter** [comment]
> I wonder if we should rename manuscript.pdf to be like manuscript-jobid.pdf

Definitely.  This would be easy to do in the AppVeyor scripts.  We could append the AppVeyor job id or build id or the git commit hash.  What do you prefer?

> Also is there a way to suppress notifications for a PR

I haven't figured out how to do that yet.

**Comment by dhimmel** [comment]
> We could append the AppVeyor job id or build id or the git commit hash.

Whichever one exactly matches the scope/provenance of these artifacts. I don't think it would be commit since CI can be rerun. However, possibly we would want both like `manuscript-jobid-commit.pdf`. This way they'll sort in order but also have the commit info which is important for identification. Perhaps we can get rid of the `output\` in the artifact?

**Pull request merged**
